### ISSUE TITLE
[Suggestion] Alphabetical Order

### ISSUE THREAD

**Issue by LuanTeles** [yne/psndl#10]
I liked the main page that displays the recommended ones, but can links to access the database in alphabetical/ per letter order be added?

**Comment by 24kushang** [comment]
Could you please elaborate the requirements a bit. I think I can help out in resolving this issue

**Comment by LuanTeles** [comment]
Something really simple like this

![image](https://github.com/yne/psndl/assets/110236244/73d81349-cb57-4ffa-be86-cb9a457cb182)


so the user can select the letter and see all the content that starts with it

**Comment by 24kushang** [comment]
I will try to implement it and send the functional code by this weekend. Please assign me this issue

**Comment by yne** [comment]
I made the change here https://github.com/yne/psndl/commit/82cf1b6c91453c5870bd7f8930e06e5f997ab0b0
- List up to 999 entries (instead of 50) for startsWith queries (`^`)
- Improved performance by calling `innerHTML` only once

@LuanTeles @24kushang : Can you tell me if it's working on PS3 both silk+webkit engine ?

I also enabled the discussions feature in this repo https://github.com/yne/psndl/discussions

**Comment by LuanTeles** [comment]
Working perfectly fine, thanks
